language: php
php:
  - 5.6
  - 7.0.4
  - nightly

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source
  
script:
  - mkdir -p build/logs
  - ./vendor/bin/phpunit -c phpunit.xml --debug --coverage-clover build/logs/clover.xml
  
after_script:
  - php vendor/bin/coveralls -v
